apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-live-claim

spec:
  storageClassName: suibian
  accessModes:
    - ReadWriteOnce
#    - ReadOnlyMany
#    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


  